### ISSUE TITLE
throw error on MAC OS X 

### ISSUE THREAD

**Issue by aozora** [akoenig/express-lingua#11]
when guru.js loop in the locales folder, if it find the ".DS_Store" it throws an error!
please add a filter to the cycle!

**Comment by akoenig** [comment]
Hey aozora,

thanks for your suggestion. You're absolutely right. I'm currently working on a minor release in which I will integrate this filter.

All the best,
André

**Comment by akoenig** [comment]
Okay, now available in release 0.3.2.
