### ISSUE TITLE
Change the language server side

### ISSUE THREAD

**Issue by guidone** [akoenig/express-lingua#12]
This is the scenario:

PayPal sends a confirmation for a payment and mail is sent back to user with the receipt of the purchase: the language of the email must be inferred from the locale of the user and not from the PayPale web bot/user agent

would be nice to be able to access to all language resources and pick up one manually (currently the complete set of resource/languages are private inside guru.js)

Thanks

**Comment by ghost** [comment]
You can add a middleware before lingua and manually set `req.query['lang']`
