### ISSUE TITLE
How to use HTML Tags within the translations?

### ISSUE THREAD

**Issue by joafeldmann** [akoenig/express-lingua#14]
I'd like to do something like this:

{
        "TOS": "....<a href='#'>Nuzungsbedingungen</a>..."
}

But the tag is not displayed as HTML. I am using handlebarsjs.

**Comment by akoenig** [comment]
If I understand you right then you would like to flavor your language files with HTML tags, right? I would suggest to avoid mixing HTML and the data in the resource files. From my point of view it would be a more cleaner way to maintain the HTML tags in the right place (the template) and inject the "readable" data (the translations) from the resource files via lingua into the templates.

**Comment by joafeldmann** [comment]
I understand your point of view, but that would make things unnecessary complex.

``` html
{{ TOS_MSG_1 }} <a href="#">{{ TOS }}</a> {{ TOS_MSG_2 }}.
```

``` javascript
// de.json
{
    "TOS_MSG_1": "Indem Du auf diesen Button klickst, stimmst Du unseren",
    "TOS": "Nutzungsbedingungen",
    "TOS_MSG_2": "zu"
}

// en.json
{
    "TOS_MSG_1": "By clicking the button, you agree to the",
    "TOS": "terms",
    "TOS_MSG_2": "below"
}
```

I think it would be nicer to write it as follows cause it makes you more flexible structuring your sentences.

``` javascript
// de.json
{
    'TOS': 'Indem Du auf diesen Button klickst, stimmst Du unseren <a href="">Nutzungsbedingungen</a> zu.'
}

// en.json
{
    'TOS': 'By clicking the button, you agree to the <a href="">terms</a> below'
}
```

**Comment by goloroden** [comment]
I don't understand the problem right now.

@joafeldmann You just said that

> the tag is not displayed as HTML

What exactly does that mean? Is it not rendered at all? Does an error message appear? Is it rendered and escaped? ...?

PS: I agree with @akoenig that it's not a good idea to mix HTML and text within a resource file, but nevertheless I understand your issue that it would be way too complicated if you didn't mix it.

**Comment by joafeldmann** [comment]
Sorry for the bad explanation (and not using the markdown above). It is not rendered at all. 

``` Javascript
{
    'TOS': 'By clicking the button, you agree to the <a href="">terms</a> below'
}
```

Result in the view to:

``` html
By clicking the button, you agree to the <a href="">terms</a> below
```

I like the way the doing it in brackets.io: https://github.com/adobe/brackets/blob/master/src/nls/root/strings.js 
They're using RequireJS i18n module (https://github.com/requirejs/i18n).

**Comment by goloroden** [comment]
To me this looks like as if you forgot to tell your templating engine that the output should not be escaped. You need to change this.

In handlebars you can achieve this by using triple braces instead of double braces. So instead of

```
{{TOS}}
```

you need to use:

```
{{{TOS}}}
```

That should fix your issue.

**Comment by joafeldmann** [comment]
Thanks, that's it!

**Comment by goloroden** [comment]
You're welcome :-)
