### ISSUE TITLE
"Hot Deployment" for resource files

### ISSUE THREAD

**Issue by akoenig** [akoenig/express-lingua#2]
At the moment the resource files will be loaded during application startup. So changes on resource files will only take effect when the server restarts.

It would be cool to have a "hot deployment" for resource files. So if something has changed in the directory: reload the resource cache!

**Comment by akoenig** [comment]
"Filesystem-Watcher" with [node-walk](https://github.com/coolaj86/node-walk)?

**Comment by goloroden** [comment]
I'm not sure whether I would put too much effort into this.

Reason: I think it's rare that you'll need this feature. This is useful only if a translation changes, but no key is added or modified. So basically this comes down to fixing typos in translations.

In all other cases, where new keys are added or existing keys are changed, you need to redeploy your whole application anyway (at least the templates).

So, I'm not sure if this is such a useful feature.

It's nice to have, yes, but at least IMHO no must-have.

**Comment by akoenig** [comment]
I totally agree. I did not consider the fact with the template redeployment. So in the end it is a "nice to have" - absolutely.
