### ISSUE TITLE
little issue when reading i18n directory

### ISSUE THREAD

**Issue by mglcel** [akoenig/express-lingua#5]
putting i18n/ directory in svn creates a .svn directory with is interpreted by lingua.

Modified guru.js:60 :

```
    files.forEach(function(file) {
```
- ```
         if (fs.statSync(path + file).isFile()) {
          var content = fs.readFileSync(path + file);
  
          var resource = { 
              locale: file.replace(that.configuration.resources.serialisation, ''),
              content: JSON.parse(content)
          };  
  
          that.resources.push(resource);
  ```
-            }  
      });

**Comment by akoenig** [comment]
You're absolutely right. Thank you :)

I've added that right away.
