### ISSUE TITLE
Express 2.4.7 compatibility

### ISSUE THREAD

**Issue by mglcel** [akoenig/express-lingua#6]
Hi, in order to get lingua running with Express 2.4.7, i have made a simple modification in lingua.js, not sure of what's occured with this version...

I also added a '_' var which permits a direct access to the i18n 'content', simplifying the templates definition, using for instance in jade #{_.description}, #{lingua.content.description} is already accessible.., don't know if its a feature you want to keep.

The diff below (from 0.2.1) :

```
lingua.js
71a72,94
>     //     The middleware function.
>     //
>     // description:
>     //     This function will be called on every single
>     //     HTTP request.
>     //
>     var lingua = function (req, res) {
>         //
>         // Determine the locale in this order:
>         // 1. URL query string, 2. Cookie analysis, 3. header analysis
>         //
>         var locales = trainee.determineLocales(req, res);
> 
>         var resource = guru.ask(locales);
>         var locale = resource.locale;
> 
>         trainee.persistCookie(req, res, locale);
> 
>         return resource;
>     };
> 
>     //
>     // summary:
108a132,134
>             if ( ! res.lingua ) {
>                 res.lingua = lingua(req, res);
>             }
109a136,138
>         },
>         _: function(req, res) {
>             return res.lingua.content.content;
113,134c142,143
<     //
<     // summary:
<     //     The middleware function.
<     //
<     // description:
<     //     This function will be called on every single
<     //     HTTP request.
<     //
<     return function lingua(req, res, next) {
<         //
<         // Determine the locale in this order:
<         // 1. URL query string, 2. Cookie analysis, 3. header analysis
<         //
<         var locales = trainee.determineLocales(req, res);
< 
<         var resource = guru.ask(locales);
<         var locale = resource.locale;
< 
<         trainee.persistCookie(req, res, locale);
< 
<         res.lingua = resource;
< 

---
>     return function (req, res, next) {
>         res.lingua = lingua(req, res);
136,137c145,146
<     };
< };

---
>     }
> };
```

**Comment by akoenig** [comment]
Hey, please excuse my stupid question, but I don't understand what you mean exactly. Do you want me to add the "_" style to lingua for a smarter template access or did you identify a problem with current release?

**Comment by mglcel** [comment]
The two ones in fact :)

The '_' is just a cool feature, but it's just a suggestion, i don't want to interfere with your plans about lingua.

The important point is the correction of what seems to be a bug with Express > 2.4.7.

The dynamicViewHelper is called before the setting of res.lingua, i've then added a simple check in the first one. If not set, i ask for its assignation, which cause a very little modification on the main returned lingua function.

I can send you the complete modified lingua.js file if you prefer.

++

**Comment by akoenig** [comment]
Hey, ah okay I see. I like the idea of a shorthand notation for the templates, but maybe we could find another character, because of the collision with the "underscore" library. What do you think?

The Bug :) I can not reproduce the problem. If I start the example app and put some debug statements into lingua I can see that the view helper will be called after the resource was loaded. Can you send me a test scenario where you identified the problem?

**Comment by mglcel** [comment]
I found it.

The 'bug' occurs when i set lingua after express router, in this configuration for instance, from a test server.js :

```
var app     = express.createServer();

app.set( 'views', __dirname );

app.use( express.logger() );
app.use( express.bodyParser() );
app.use( express.cookieParser() );
app.use( express.methodOverride() );
app.use( express.errorHandler( { dumpExceptions: true, showStack: true } ) );  
app.use( app.router );

app.use(lingua(app, {
    defaultLocale: 'en',
    path: 'i18n' 
}));
```

But all works fine if i set it first :

```
var app     = express.createServer();

app.set( 'views', __dirname );

app.use(lingua(app, {
    defaultLocale: 'en',
    path: 'i18n' 
}));

app.use( express.logger() );
app.use( express.bodyParser() );
app.use( express.cookieParser() );
app.use( express.methodOverride() );
app.use( express.errorHandler( { dumpExceptions: true, showStack: true } ) );  
app.use( app.router );
```

Don't know if the best way is to just notify users in the documentation about the order or to integrate my patch or something of this sort in order to be order-agnostic... ?

I think it's a mistake to not set app.router in last position, but it could also be cool to allow any ordering for lingua, ensuring less questions from users in such a case..

++

**Comment by mglcel** [comment]
about the underscore, i have no idea of other shorthand, i used to underscore because it seems to be a standard in many translation systems but any other simple non-interfering character should be ok i suppose..

Perhaps just 'L' as 'l'ingua ?

++

**Comment by mglcel** [comment]
Hi André,

i've added some features needed by my project :

1/ i need to load localization files with a corporate format
2/ i need to be able to parse parameters in localized sentences

so, using the options, you can define one or both of two new parsers :

```
        app.use(lingua(app, {
            defaultLocale: 'en',
            path: i18n_dir,
            resourceParser: linguaResourceParser,
            sentenceParser: linguaSentenceParser
        }));
```

with :

```
    linguaResourceParser = function(path, file) {
        (...)
        return {
            locale: locale,
            content: translates
        };
    };
```

and

```
    linguaSentenceParser = function(sentence, arrayParams) {
        (...)
        return sentence;
    }
```

I modified the '_' shorthand with a 'L' function, so you can use it like this (here in jade) :

```
p #{L('freelance.visites')}
p #{L('recruteurs.recherchepourdiffuserannoncepro.form.confirm.1', 42, 'langue')}
```

If you're interested i can send you the diff, it's very minor code changes but perhaps you are not interested or you want to make your own implementation..

I guess that the next change for me will be in jade in order to allow something like this :

```
_{'recruteurs.recherchepourdiffuserannoncepro.form.confirm.1', myVar, 'langue'}
```

or similar..

**Comment by akoenig** [comment]
Hey, sorry for my late response and thank you for your explanation. What do you think? Can you prepare a pull request with your changes?

**Comment by karlguillotte** [comment]
Hi akoenig,

I am having similar issues with Express 2.5.2 as well. 

BTW - Good and simple library.

**Comment by mglcel** [comment]
hi karl, you have to ensure that your app.router is the last call and all should be fine.
++

**Comment by akoenig** [comment]
Hey Karl,

thank you for your praise and thank you mgIcel for your solution. Well, I think that I have to fix the Readme and point this out.

/andré
