### ISSUE TITLE
How do I insert dynamic data to a translated string?

### ISSUE THREAD

**Issue by goloroden** [akoenig/express-lingua#7]
I have the following situation: A website contains a string that is translated using express-lingua.
Inside this string there is a value that needs to be inserted dynamically, as it comes from a database. So basically I have a string in my i18n file which looks like:

bla bla bla %d bla bla bla

This %d is the placeholder for the dynamic data.
On each request I load this data from the database to have a "fresh" value.

So how do I combine the i18n resource string and the dynamic data?

I've tried by accessing res.lingua.content.foo and replacing %d by the value by using util.format. This works on the first request, but since the i18n value is cached, on each further request there is no %d so the value gets added to the i18n string.

What is the best way to solve this?

**Comment by akoenig** [comment]
I think this is an issue for the template engine of your choice. Look at this ticket in the mustache project over here: https://github.com/janl/mustache.js/pull/139

The problem is that the dynamic view helper in Express.js does not allow "parameter passing". A Q&D solution could be:

``` javascript
app.get('/', function(req, res){
    // Create a copy from the i18n resource
    var i18n = Object.create(res.lingua.content);

    // TODO: Replace the %d with your dynamic data.

    // Render template
    res.render('template', i18n);
});

```

And then you could use 'i18n' instead of 'lingua' in your templates.

**Comment by akoenig** [comment]
Wait :) I think that I've found a solution. I will implement a new helper for this issue.

**Comment by akoenig** [comment]
Okay, I've implemented a new helper 'linguac' with which it is possible to compile dynamic data into a resource within the template.

Example:

``` javascript
app.get('/', function(req, res){
    res.render('index', {
        person: {
            name: 'Thomas',
            age: Math.round(Math.random()*100)
        }
    });
});
```

Template:

``` html
<!-- lingua.your.i18n.string = "Hallo {name}. Du bist {age} Jahre alt." -->
<p>${linguac(lingua.your.i18n.string, person)}</p>
```

I've also included this example in the demo app. I would like to create a nicer scenario for the example app after testing this new feature.

What do you think? Do you want to test it too? Thanks in advance :)

**Comment by goloroden** [comment]
Basically, I'm fine with this, hence +1.

**Comment by goloroden** [comment]
One more question - if I want to include {name} without using it as a placeholder - should I escape it, or ...?

**Comment by akoenig** [comment]
Oh, this is a good point. I did not implement anything for handling this case yet. The parser will ignore escaping the placeholder at the moment. I would like to ship a solution for this task in the 0.3.1 release. What do you think?

**Comment by goloroden** [comment]
I think it should be the usual \ prefix, so:

\{foo}
